# These are supported funding model platforms

# GitHub Sponsors
github: [Beam]

# Open Collective
# open_collective: beam

# Patreon
# patreon: beam

# Ko-fi
ko_fi: I3I31MM8N2

# Buy Me a Coffee
# buy_me_a_coffee: beam

# Custom URLs (up to 4)
# custom: ['https://beam.com/donate', 'https://paypal.me/beam']
